version: '3'

services:
  app:
    build:
      context: ./
    container_name: tg_logger
    env_file:
      - .env
    restart: always
    volumes:
      - tg_logger-storage:/root/app
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  tg_logger-storage:
